"use strict"
// this file reflects the mapping of the JSON-LD context file at http://www.w3.org/ns/odrl.jsonld
exports.action = "http://www.w3.org/ns/odrl/2/action"
exports.assignee = "http://www.w3.org/ns/odrl/2/assignee"
exports.assigner = "http://www.w3.org/ns/odrl/2/assigner"
exports.consequence = "http://www.w3.org/ns/odrl/2/consequence"
exports.constraint =  "http://www.w3.org/ns/odrl/2/constraint"
exports.duty =  "http://www.w3.org/ns/odrl/2/duty"
exports.lc_and = "http://www.w3.org/ns/odrl/2/and"
exports.lc_andSequence = "http://www.w3.org/ns/odrl/2/andSequence"
exports.lc_or = "http://www.w3.org/ns/odrl/2/or"
exports.lc_xone = "http://www.w3.org/ns/odrl/2/xone"
exports.obligation =  "http://www.w3.org/ns/odrl/2/obligation"
exports.permission =  "http://www.w3.org/ns/odrl/2/permission"
exports.prohibition =  "http://www.w3.org/ns/odrl/2/prohibition"
exports.refinement =  "http://www.w3.org/ns/odrl/2/refinement"
exports.remedy = "http://www.w3.org/ns/odrl/2/remedy"
exports.source = "http://www.w3.org/ns/odrl/2/source"
exports.target = "http://www.w3.org/ns/odrl/2/target"

