"use strict"
exports.permission =  "http://www.w3.org/ns/odrl/2/permission"
exports.prohibition =  "http://www.w3.org/ns/odrl/2/prohibition"
exports.duty =  "http://www.w3.org/ns/odrl/2/duty"
exports.obligation =  "http://www.w3.org/ns/odrl/2/obligation"
exports.constraint =  "http://www.w3.org/ns/odrl/2/constraint"
exports.refinement =  "http://www.w3.org/ns/odrl/2/refinement"
