"use strict"
exports.permission =  "http://www.w3.org/ns/odrl/2/permission"
exports.prohibition =  "http://www.w3.org/ns/odrl/2/prohibition"
exports.duty =  "http://www.w3.org/ns/odrl/2/duty"
exports.obligation =  "http://www.w3.org/ns/odrl/2/obligation"
exports.remedy = "http://www.w3.org/ns/odrl/2/remedy"
exports.consequence = "http://www.w3.org/ns/odrl/2/consequence"
exports.action = "http://www.w3.org/ns/odrl/2/action"
exports.constraint =  "http://www.w3.org/ns/odrl/2/constraint"
exports.refinement =  "http://www.w3.org/ns/odrl/2/refinement"
exports.lc_or = "http://www.w3.org/ns/odrl/2/or"
exports.lc_xone = "http://www.w3.org/ns/odrl/2/xone"
exports.lc_and = "http://www.w3.org/ns/odrl/2/and"
exports.lc_andSequence = "http://www.w3.org/ns/odrl/2/andSequence"

